name: 編譯OPPO-Snapdragon660-Android-Pieの核心與Anykernel3文檔
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      rekernel:
        type: choice
        description: '是否开启RE:Kernel'                
        required: true
        default: 'false'        
        options:
        - 'true'
        - 'false'
      debug:
        type: choice
        description: '是否开启快速进入recovery模式'                
        required: true
        default: 'false'        
        options:
        - 'true'
        - 'false'
      kpm:
        type: choice
        description: '是否开启KPM'                
        required: true
        default: 'false'        
        options:
        - 'true'
        - 'false'                
      ksubranch:
        type: choice
        description: '請選擇KernelSU的第三方分叉'                
        required: true
        default: 'sukisu'        
        options:
        - 'nongki'
        - 'sukisu'
      branch:
        type: choice
        description: '請選擇第三方KernelSU的分叉'                
        required: true
        default: 'nongki'        
        options:
        - 'nongki'
        - 'main'
      device:
        type: choice
        description: '設備名稱'        
        required: true
        options:
        - 'OPPO R11'
        - 'OPPO R11t'
        - 'OPPO R11 Plus'
        - 'OPPO R11 Plusk'
        - 'OPPO R11 Pluskt'
        - 'OPPO R11s'
        - 'OPPO R11sPlus'
        - 'OPPO R11sPlust'
      target:
        type: choice
        description: '設備內核代號'
        required: true
        options:
        - '16051'
        - '16052'
        - '16103'
        - '16118'
        - '16116'
        - '17011'
        - '17013'
        - '17021'
        - '17023'

jobs:
  install:
    name: ${{ github.actor }}編譯嘅${{ github.event.inputs.device }}核心
    runs-on: ubuntu-22.04
    steps:

      - name: 獲取分支嘅名稱
        id: branch-names
        uses: tj-actions/branch-names@v8

      - name: 設定5GIB嘅SWAP
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 5

      - name: 安裝所需嘅環境
        run: |
          sudo apt-get update
          sudo apt-get install git automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 lib32ncurses5-dev libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler python2 python3
          mkdir -p $GITHUB_WORKSPACE/workdir
          cd $GITHUB_WORKSPACE/workdir
          echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M")" >> $GITHUB_ENV

      - name: 獲取zyc-clang20工具鏈
        run: |
          wget https://github.com/ZyCromerZ/Clang/releases/download/20.0.0git-20241109-release/Clang-20.0.0git-20241109.tar.gz -O $GITHUB_WORKSPACE/workdir/zyc_clang20.tar.gz
          mkdir $GITHUB_WORKSPACE/workdir/clang
          tar zxvf $GITHUB_WORKSPACE/workdir/zyc_clang20.tar.gz -C $GITHUB_WORKSPACE/workdir/clang
  
      - name: 獲取${{ github.event.inputs.device }}嘅核心源碼
        run: |
          git clone --recursive https://github.com/$GITHUB_REPOSITORY/ -b ${{ steps.branch-names.outputs.current_branch }} --depth 1 $GITHUB_WORKSPACE/workdir/source

      - name: 設定ccache嘅容量
        uses: hendrikmuhs/ccache-action@v1.2
        with:
         key: build-kernel-mido-kernel
         max-size: 2G

      - name: 添加RE:Kernel功能
        run: |
          if [ "${{ github.event.inputs.rekernel }}" == "true" ]; then
             echo -e "\nCONFIG_REKERNEL=y"  >> $GITHUB_WORKSPACE/workdir/source/arch/arm64/configs/sdm660-perf_defconfig
          fi

      - name: 添加快速进入recovery模式功能
        run: |
          if [ "${{ github.event.inputs.debug }}" == "true" ]; then
             echo -e "\nCONFIG_ELYSIA_DEBUG=y"  >> $GITHUB_WORKSPACE/workdir/source/arch/arm64/configs/sdm660-perf_defconfig
          fi

      - name: 添加 Rissu
        run: |
          if [ "${{ github.event.inputs.ksubranch }}" == "rissu" ]; then
             curl -LSs "https://raw.githubusercontent.com/rsuntk/KernelSU/main/kernel/setup.sh" | bash -s ${{ github.event.inputs.branch }}
          fi

      - name: 添加 Sukisu Ultra
        run: |
          if [ "${{ github.event.inputs.ksubranch }}" == "suskisu" ]; then
             curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/d2ab325e1863c6abae1935d5f617a92fb1574983/kernel/setup.sh" | bash -s ${{ github.event.inputs.branch }}
          fi

      - name: 編譯${{ github.event.inputs.device }}核心
        run: |
          export KBUILD_BUILD_HOST=Github-Action
          export KBUILD_BUILD_USER=$(echo ${{ github.actor }})
          export ARCH="arm64"
          export SUBARCH="arm64"
          export PATH="$GITHUB_WORKSPACE/workdir/clang/bin/:$PATH"
          export CROSS_COMPILE="aarch64-linux-gnu-"
          cd $GITHUB_WORKSPACE/workdir/source
          export OPPO_TARGET_DEVICE="MSM_${{ github.event.inputs.target }}"
          make O=out sdm660-perf_defconfig CC="ccache clang"
          make -j$(nproc --all) O=out CC="ccache clang" 2>&1 | tee kernel.log

      - name: 上傳日志
        uses: actions/upload-artifact@v4
        with:
          name: android_kernel_oppo_sdm660_${{ github.event.inputs.target }}_${{ env.BUILD_TIME }}_kernel.log
          path: workdir/source/kernel.log

      - name: 檢查${{ github.event.inputs.device }}嘅內核文檔
        run: |
          cd $GITHUB_WORKSPACE/workdir/source
          if [ -f out/arch/arm64/boot/Image.gz-dtb ]; then
              echo "CHECK_FILE_IS_OK=true" >> $GITHUB_ENV
          else
              echo "Kernel output file is empty"
              exit 1
          fi

      - name: 修補KPM
        if: env.CHECK_FILE_IS_OK == 'true'
        run: |
          if [ "${{ github.event.inputs.kpm }}" == "true" ]; then
             mkdir $GITHUB_WORKSPACE/workdir/SukiSU-Patch
             cd $GITHUB_WORKSPACE/workdir/SukiSU-Patch
             curl -LSs "https://raw.githubusercontent.com/ShirkNeko/SukiSU_patch/refs/heads/main/kpm/patch_linux" -o patch_linux
             cp $GITHUB_WORKSPACE/workdir/source/out/arch/arm64/boot/Image .
             cp $GITHUB_WORKSPACE/workdir/source/out/arch/arm64/boot/dts/1*/*.dtb .
             chmod +x patch_linux
             ./patch_linux
             mv -f oImage Image
             gzip -k Image Image.gz
             cat Image.gz *.dtb > Image.gz-dtb
          fi

      - name: 制作${{ github.event.inputs.device }}嘅Anykernel3文檔
        if: env.CHECK_FILE_IS_OK == 'true'
        run: |
          git clone https://github.com/$GITHUB_REPOSITORY/ -b prebuilt_ak3 --depth 1 $GITHUB_WORKSPACE/workdir/ak3
          rm -r $GITHUB_WORKSPACE/workdir/ak3/.git
          if [ "${{ github.event.inputs.kpm }}" == "true" ]; then 
             cp $GITHUB_WORKSPACE/workdir/SukiSU-Patch/Image.gz-dtb $GITHUB_WORKSPACE/workdir/ak3
          else
             cp $GITHUB_WORKSPACE/workdir/source/out/arch/arm64/boot/Image.gz-dtb $GITHUB_WORKSPACE/workdir/ak3
          fi

      - name: 上傳${{ github.event.inputs.device }}嘅AnyKernel3文檔
        if: env.CHECK_FILE_IS_OK == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: AnyKernel3_oppo_sdm660_${{ github.event.inputs.target }}_${{ env.BUILD_TIME }}
          path: workdir/ak3/*